services:
  spring-jni:
    image: 'camilosuarez137/analisis-numerico-service:latest'
    ports:
      - '8083:8080'
    networks:
      - red-backend-app
networks:
  red-backend-app:
    driver: bridge


