/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcalculadora_CalculadoraAnalisis */

#ifndef _Included_libcalculadora_CalculadoraAnalisis
#define _Included_libcalculadora_CalculadoraAnalisis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcalculadora_CalculadoraAnalisis
 * Method:    interpolacion
 * Signature: ([[DD)D
 */
JNIEXPORT jdouble JNICALL Java_libcalculadora_CalculadoraAnalisis_interpolacion
  (JNIEnv *, jobject, jobjectArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
